# Adiciona Caminhao
POST http://localhost:8080/caminhoes
Content-type: application/json

{
  "placa": "MUW-7896",
  "tipo": "carreta"
}
###
GET http://localhost:8080/caminhoes
###
GET http://localhost:8080/caminhoes/GVP-3672
###
PUT http://localhost:8080/caminhoes/MUW-7896/embalagens/adicionar
Content-Type: application/json

{
  "embalagens": [
    { "codigo": "4321", "quantidade": 5 }
  ]
}
###
PUT http://localhost:8080/caminhoes/944n223/embalagens/remover
Content-Type: application/json

{
  "embalagens": [
    { "codigo": "2321", "quantidade": 1 }
  ]
}
