# Adiciona Embalagem
POST http://localhost:8080/embalagens
Content-type: application/json

{
  "codigo": "4321",
  "descricao": "peças de engate",
  "fornecedores": ["E022"],
  "tipo": "STANDARD",
  "criticalidade": "MEDIA",
  "altura": 2,
  "largura": 2,
  "comprimento": 2
}
###
GET http://localhost:8080/embalagens
###
GET http://localhost:8080/embalagens/1234
###
PUT http://localhost:8080/embalagens/2321
Content-Type: application/json

{
  "descricao" : "gerais",
  "fornecedores": ["E201"],
  "tipo" : "fluxo",
  "criticalidade" : "baixa",
  "altura" : 1,
  "comprimento" : 7,
  "largura" : 2
}
###
DELETE http://localhost:8080/embalagens/
###