# Adiciona Fornecedor
POST http://localhost:8080/fornecedores
Content-type: application/json

{
  "codigo": "E14",
  "nome": "andre",
  "frete": "FIB"
}
###
GET http://localhost:8080/fornecedores
###
GET http://localhost:8080/fornecedores/E202
###
PUT http://localhost:8080/fornecedores/E201
Content-Type: application/json

{
  "nome" : "teste da silva",
  "frete": "FOB"
}
###
DELETE http://localhost:8080/fornecedores/E201
###
