# Adiciona Fornecedor
POST http://localhost:8080/fornecedores
Content-type: application/json

{
  "codigo": "E202",
  "nome": "Marquinhos",
  "frete": "CIF"
}
###

GET http://localhost:8080/fornecedores
###

# Adiciona Embalagem
POST http://localhost:8080/embalagens
Content-type: application/json

{
  "codigo": "5738",
  "descricao": "gerais",
  "fornecedores": ["E202", "E201"],
  "tipo": "Fluxo",
  "criticalidade": "alta",
  "altura": 2,
  "largura": 4,
  "comprimento": 5
}
###

GET http://localhost:8080/embalagens
###

GET http://localhost:8080/embalagens/8359
###